Repository lnflash/flash-mobile, pull requests merged in 2024-08, with the labels that each got.

#212 Currency settings improvements
  app/screens/card-screen/card.tsx
  app/screens/settings-screen/display-currency-screen.tsx
Labels: enhancement

#218 add test env
  app/config/galoy-instances.ts
Labels: High

#220 fixed color style issue on currency settings screen confirm button
  app/screens/settings-screen/display-currency-screen.tsx
Labels: bug

#190 Implement nfc feature for breez BTC wallet and show insufficient balance error if funds not enough in the nfc card
  app/components/modal-nfc/modal-nfc.tsx
  app/screens/receive-bitcoin-screen/receive-screen.tsx
  app/screens/receive-bitcoin-screen/use-receive-bitcoin.ts
Labels: enhancement

#219 add welcome screens and help icon
  app/assets/images/welcome-1.png
  app/assets/images/welcome-2.png
  app/assets/images/welcome-3.png
  app/navigation/root-navigator.tsx
  app/navigation/stack-param-lists.ts
  app/screens/get-started-screen/get-started-screen.tsx
  app/screens/home-screen/home-screen.tsx
  app/screens/send-bitcoin-screen/use-send-payment.ts
  app/screens/welcome-screen/index.ts
  app/screens/welcome-screen/index.types.d.ts
  app/screens/welcome-screen/welcome-screen.tsx
  app/store/persistent-state/state-migrations.ts
  package.json
Labels: enhancement

#224 fix email display on settings screen
  app/graphql/generated.ts
  app/screens/email-registration-screen/email-registration-validate.tsx
  app/screens/settings-screen/account/account-screen.tsx
  app/screens/settings-screen/account/settings/email.tsx
  app/screens/settings-screen/settings/nostr-secret.tsx
  package.json
Labels: bug

#242 Fix codegen
  app/graphql/front-end-queries.ts
  app/graphql/generated.gql
  app/graphql/generated.ts
  app/hooks/use-logout.ts
  app/screens/settings-screen/settings-screen.tsx
  app/screens/settings-screen/totp.tsx
  codegen.yml
  e2e/utils/graphql.ts
Labels: bug
